# To enable deployment, obtain your deployment token from the Azure Portal for your Static Web App and add it as a repository secret named AZURE_STATIC_WEB_APPS_API_TOKEN in GitHub.
# See: https://docs.microsoft.com/en-us/azure/static-web-apps/deployment-token

name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Frontend
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies and build frontend
        run: |
          npm install
          npm run build
        working-directory: frontend

      - name: Deploy to Azure Static Web Apps
        id: swa-deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e., PR comments)
          action: 'upload'
          app_location: "/frontend"
          output_location: "dist"
          skip_deploy_on_missing_secrets: true 